version: "3.7"
services:
  front:
    container_name: cd-entertainment-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - cb-network
    restart: always
    environment:
      - SPOTIFY_CLIENT_ID=e385c59f1a5649db8c6f952be507d1e9
      - SPOTIFY_CLIENT_SECRET=253cd4b25c01439baeeaf289514a614d
      - NEXTAUTH_SECRET=J1OLjcHlKfBi3oZz8P9x
networks:
  cb-network:
    driver: bridge