version: "3.7"
services:
  front:
    container_name: cd-entertainment-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - ${APP_PORT}:3000
    networks:
      - cb-network
    restart: always
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
networks:
  cb-network:
    driver: bridge