#!/bin/sh
echo "Check that we have the env vars"
test -n "$SPOTIFY_CLIENT_ID"
find /app/.next \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i "s#APP_SPOTIFY_CLIENT_ID#$SPOTIFY_CLIENT_ID#g"
test -n "$SPOTIFY_CLIENT_SECRET"
find /app/.next \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i "s#APP_SPOTIFY_CLIENT_SECRET#$SPOTIFY_CLIENT_SECRET#g"
test -n "$NEXTAUTH_SECRET"
find /app/.next \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i "s#APP_NEXTAUTH_SECRET#$NEXTAUTH_SECRET#g"
test -n "$NEXT_PUBLIC_URL_BACKEND"
find /app/.next \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i "s#APP_NEXT_PUBLIC_URL_BACKEND#$NEXT_PUBLIC_URL_BACKEND#g"
test -n "$NEXT_PUBLIC_URI_SEARCH_SPOTIFY"
find /app/.next \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i "s#APP_NEXT_PUBLIC_URI_SEARCH_SPOTIFY#$NEXT_PUBLIC_URI_SEARCH_SPOTIFY#g"
echo "Starting Nextjs"
exec "$@"